test

diff --git a/.github/workflows/deploy-production.yml b/.github/workflows/deploy-production.yml
--- a/.github/workflows/deploy-production.yml
+++ b/.github/workflows/deploy-production.yml
@@ -25,7 +25,7 @@ jobs:
       - name: Deploy to production server
         uses: appleboy/ssh-action@master
         env:
-          GITHUB_REF: ${{ github.ref }}
+          TAG_NAME: ${{ github.ref_name }}
         with:
           host: ${{ vars.HOST }}
           username: ${{ vars.SSH_USERNAME }}
@@ -35,9 +35,9 @@ jobs:
             cd /home/hallofheroes/prod
             
             # Обновление кода из репозитория и переключение на тег
-            git fetch --all --tags
-            git checkout ${GITHUB_REF#refs/*/}
-            echo "Checkout version ${GITHUB_REF#refs/*/} at $(date)"
+            git fetch --all --tags --force || { echo "Failed to fetch tags"; exit 1; }
+            git checkout $TAG_NAME || { echo "Failed to checkout $TAG_NAME"; exit 1; }
+            echo "Checkout version $TAG_NAME at $(date)"
             
             # Установка и сборка бэкенда
             cd apps/backend
